let data=null;const $=s=>document.querySelector(s);const escapeHtml=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function load(){const r=await fetch('../data/content.json',{cache:'no-store'});data=await r.json();render()}
function render(){renderSchedules();renderSongs();renderAnnouncements()}
function input(label,key,val,full=false){return `<label class="${full?'full':''}">${label}<input data-key="${key}" value="${escapeHtml(val??'')}"></label>`}
function renderSchedules(){const el=$('#schedules');el.innerHTML=data.schedules.map((s,i)=>`<article class="item" data-index="${i}" data-type="schedule">${input('Date','date',s.date)}${input('Time','time',s.time)}${input('Title','title',s.title)}${input('Type','type',s.type)}${input('Location','location',s.location)}${input('Description','description',s.description,true)}<div class="actions"><button class="remove" data-remove="schedule">Delete</button></div></article>`).join('')||'<p>No schedules.</p>';wireItems()}
function renderSongs(){const el=$('#songs');el.innerHTML=data.songs.map((s,i)=>`<article class="item" data-index="${i}" data-type="song">${input('Title','title',s.title)}${input('Artist','artist',s.artist)}${input('Category','category',s.category)}${input('YouTube URL','youtube',s.youtube,true)}<div class="actions"><button class="remove" data-remove="song">Delete</button></div></article>`).join('')||'<p>No songs.</p>';wireItems()}
function renderAnnouncements(){const el=$('#announcements');el.innerHTML=data.announcements.map((s,i)=>`<article class="item" data-index="${i}" data-type="announcement">${input('Title','title',s.title)}${input('Date','date',s.date)}${input('Time','time',s.time)}${input('Text','text',s.text,true)}<div class="actions"><button class="remove" data-remove="announcement">Delete</button></div></article>`).join('')||'<p>No announcements.</p>';wireItems()}
function wireItems(){document.querySelectorAll('.item input').forEach(inp=>inp.addEventListener('input',e=>{const item=e.target.closest('.item');const i=Number(item.dataset.index);const key=e.target.dataset.key;const type=item.dataset.type;const arr=type==='schedule'?data.schedules:type==='song'?data.songs:data.announcements;arr[i][key]=e.target.value}));document.querySelectorAll('[data-remove]').forEach(btn=>btn.onclick=()=>{const item=btn.closest('.item');const i=Number(item.dataset.index);const type=item.dataset.type;const arr=type==='schedule'?data.schedules:type==='song'?data.songs:data.announcements;arr.splice(i,1);render()})}
$('#addSchedule').onclick=()=>{data.schedules.push({id:`s-${Date.now()}`,date:'2026-09-01',time:'09:00',title:'New Church Schedule',type:'Worship',location:'New Life Ozamiz',description:'Add schedule description.'});renderSchedules()};$('#addSong').onclick=()=>{data.songs.push({id:`m-${Date.now()}`,title:'New Worship Song',artist:'Artist',category:'Worship',youtube:'https://www.youtube.com/watch?v=',color:'purple'});renderSongs()};$('#addAnnouncement').onclick=()=>{data.announcements.push({id:`a-${Date.now()}`,title:'New Announcement',date:'2026-09-01',time:'18:00',text:'Add announcement details.'});renderAnnouncements()};
$('#downloadBtn').onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='content.json';a.click();URL.revokeObjectURL(a.href)};$('#resetBtn').onclick=()=>load();$('#loadBtn').onclick=()=>load();load().catch(()=>alert('Could not load data/content.json. Use a local web server rather than file://.'));
