const state={data:null,month:new Date(2026,7,1),songIndex:0,playing:false,filter:'All',deferredInstall:null};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const isoDate=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const formatDate=(date,time)=>new Intl.DateTimeFormat('en-PH',{weekday:'short',month:'short',day:'2-digit',hour:'numeric',minute:'2-digit',hour12:true,timeZone:'Asia/Manila'}).format(new Date(`${date}T${time}:00+08:00`));
async function load(){const r=await fetch('data/content.json',{cache:'no-store'});state.data=await r.json();renderAll();}
function renderAll(){renderContact();renderSchedules();renderSongs();renderMusic();renderCalendar();renderEvents();$('#year').textContent=new Date().getFullYear();selectNav();reveal();updateCountdown();}
function renderContact(){const c=state.data.church;$('#contactAddress').textContent=c.address;$('#phoneLink').href=`tel:${c.phone.replace(/\s/g,'')}`;$('#emailLink').href=`mailto:${c.email}`;$('#emailLink').textContent=c.email;$('#fbLink').textContent=`Facebook · ${c.facebook}`;$('#fbLink').href='https://www.facebook.com/';$('#mapLink').href=`https://maps.google.com/?q=${encodeURIComponent(c.address)}`;}
function renderSchedules(){const target=$('#scheduleGrid');const list=[...state.data.schedules].sort((a,b)=>`${a.date}${a.time}`.localeCompare(`${b.date}${b.time}`));target.innerHTML=list.slice(0,4).map(s=>`<article class="schedule-card reveal"><div class="schedule-time">${formatDate(s.date,s.time)}</div><span class="tag ${tagClass(s.type)}">${escapeHtml(s.type)}</span><h3>${escapeHtml(s.title)}</h3><p>${escapeHtml(s.location)}</p></article>`).join('');}
function renderSongs(){const filter=$('#filterRow');const cats=['All',...new Set(state.data.songs.map(s=>s.category))];filter.innerHTML=cats.map(c=>`<button class="${state.filter===c?'active':''}" data-filter="${escapeAttr(c)}">${escapeHtml(c)}</button>`).join('');$$('[data-filter]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;renderSongs()});const cards=$('#songCards');const songs=state.data.songs.filter(s=>state.filter==='All'||s.category===state.filter);cards.innerHTML=songs.map((s,i)=>`<article class="song-card reveal"><div class="song-art">${escapeHtml(s.title.split(' ').map(x=>x[0]).slice(0,2).join(''))}</div><div class="song-card-body"><span class="tag ${tagClass(s.category)}">${escapeHtml(s.category)}</span><h3>${escapeHtml(s.title)}</h3><p>${escapeHtml(s.artist)}</p><div class="song-actions"><button class="play-local" data-play="${escapeAttr(s.id)}">Play</button><a class="link-button" style="justify-content:center;align-items:center;border:1px solid #dfe3ea;border-radius:11px" href="${escapeAttr(s.youtube)}" target="_blank" rel="noreferrer">YouTube</a></div></div></article>`).join('');$$('[data-play]').forEach(b=>b.onclick=()=>{const idx=state.data.songs.findIndex(s=>s.id===b.dataset.play);if(idx>=0){state.songIndex=idx;state.playing=true;updatePlayer();scrollToMusic();}});}
function renderMusic(){const list=$('#songList');list.innerHTML=state.data.songs.map((s,i)=>`<div class="queue-item ${i===state.songIndex?'active':''}" data-q="${escapeAttr(s.id)}"><div class="queue-thumb">${escapeHtml(s.title.slice(0,2))}</div><div><strong>${escapeHtml(s.title)}</strong><small>${escapeHtml(s.artist)}</small></div><span>›</span></div>`).join('');$$('[data-q]').forEach(el=>el.onclick=()=>{state.songIndex=state.data.songs.findIndex(s=>s.id===el.dataset.q);state.playing=true;updatePlayer()});updatePlayer();}
function updatePlayer(){const s=state.data.songs[state.songIndex];if(!s)return;$('#currentTitle').textContent=s.title;$('#currentArtist').textContent=s.artist;$('#miniTitle').textContent=s.title;$('#miniArtist').textContent=s.artist;$('#youtubeLink').href=s.youtube;$('#playBtn').textContent=state.playing?'❚❚':'▶';$('#miniPlay').textContent=state.playing?'❚❚':'▶';$('#wave').classList.toggle('paused',!state.playing);$$('.queue-item').forEach((e,i)=>e.classList.toggle('active',i===state.songIndex));}
function renderCalendar(){const y=state.month.getFullYear(),m=state.month.getMonth();$('#monthTitle').textContent=new Intl.DateTimeFormat('en',{month:'long',year:'numeric'}).format(state.month);const first=new Date(y,m,1),last=new Date(y,m+1,0);const start=new Date(y,m,1-first.getDay());const days=$('#calendarDays');let html='';for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const key=isoDate(d);const other=d.getMonth()!==m;const today=key===isoDate(new Date());const has=state.data.schedules.some(s=>s.date===key);html+=`<button type="button" class="day ${other?'other':''} ${today?'today':''} ${has?'has-event':''}" data-day="${key}">${d.getDate()}</button>`;}days.innerHTML=html;$$('[data-day]').forEach(b=>b.onclick=()=>{renderAgenda(b.dataset.day);$$('.day').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});renderAgenda(isoDate(new Date(y,m,Math.min(Math.max(new Date().getDate(),1),last.getDate()))));}
function renderAgenda(day){const list=state.data.schedules.filter(s=>s.date===day);const upcoming=$('#agenda');if(!list.length){upcoming.innerHTML='<div class="agenda-item"><time>—</time><div><b>No official gatherings</b><span>Nothing scheduled for this date.</span></div></div>';return;}upcoming.innerHTML=list.map(s=>`<div class="agenda-item"><time>${escapeHtml(s.time)}</time><div><b>${escapeHtml(s.title)}</b><span>${escapeHtml(s.location)}</span></div></div>`).join('');}
function renderEvents(){const items=state.data.announcements;$('#eventGrid').innerHTML=items.map(a=>`<article class="event-card reveal"><div class="event-date">${formatDate(a.date,a.time)}</div><h3>${escapeHtml(a.title)}</h3><p>${escapeHtml(a.text)}</p></article>`).join('');}
function updateCountdown(){const first=[...state.data.schedules].sort((a,b)=>`${a.date}${a.time}`.localeCompare(`${b.date}${b.time}`)).find(s=>new Date(`${s.date}T${s.time}:00+08:00`).getTime()>Date.now())||state.data.schedules[0];const target=new Date(`${first.date}T${first.time}:00+08:00`).getTime();$('#heroNextTitle').textContent=first.title;$('#heroNextMeta').textContent=`${new Intl.DateTimeFormat('en-PH',{month:'long',day:'numeric',year:'numeric',timeZone:'Asia/Manila'}).format(new Date(target))} · ${new Intl.DateTimeFormat('en-PH',{hour:'numeric',minute:'2-digit',hour12:true,timeZone:'Asia/Manila'}).format(new Date(target))} · ${first.location}`;function tick(){let d=Math.max(0,target-Date.now());const v=[Math.floor(d/86400000),Math.floor(d/3600000)%24,Math.floor(d/60000)%60,Math.floor(d/1000)%60];$$('#countdown b').forEach((e,i)=>e.textContent=String(v[i]).padStart(2,'0'));}tick();clearInterval(state.countTimer);state.countTimer=setInterval(tick,1000);}
function scrollToMusic(){document.querySelector('#music').scrollIntoView({behavior:'smooth'});}
function selectNav(){const links=$$('.desktop-links a');const sections=['home','schedule','calendar','music','songs','events','about','contact'];const obs=new IntersectionObserver(es=>{const visible=es.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(!visible)return;links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${visible.target.id}`));},{rootMargin:'-30% 0px -50% 0px',threshold:[0,.2,.4,.6]});sections.map(id=>document.getElementById(id)).filter(Boolean).forEach(s=>obs.observe(s));}
function reveal(){const els=$$('.reveal:not(.in)');if(!('IntersectionObserver'in window)){els.forEach(e=>e.classList.add('in'));return;}const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.12});els.forEach(e=>io.observe(e));}
function tagClass(t){const s=(t||'').toLowerCase();if(s.includes('youth'))return'youth';if(s.includes('prayer'))return'prayer';if(s.includes('bible'))return'bible';return'worship'}
function escapeHtml(s=''){return String(s).replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function escapeAttr(s=''){return escapeHtml(s).replace(/`/g,'&#96;')}
$('#prevBtn').onclick=()=>{state.songIndex=(state.songIndex-1+state.data.songs.length)%state.data.songs.length;state.playing=true;updatePlayer()};$('#nextBtn').onclick=()=>{state.songIndex=(state.songIndex+1)%state.data.songs.length;state.playing=true;updatePlayer()};$('#playBtn').onclick=()=>{state.playing=!state.playing;updatePlayer()};$('#miniPrev').onclick=$('#prevBtn').onclick;$('#miniNext').onclick=$('#nextBtn').onclick;$('#miniPlay').onclick=$('#playBtn').onclick;$('#playAllBtn').onclick=()=>{state.songIndex=0;state.playing=true;updatePlayer()};$('#shuffleBtn').onclick=()=>{state.songIndex=Math.floor(Math.random()*state.data.songs.length);state.playing=true;updatePlayer()};$('#queueToggle').onclick=()=>document.querySelector('.queue').classList.toggle('expanded');
$('#themeBtn').onclick=()=>{document.body.classList.toggle('midnight');localStorage.setItem('nlo_theme',document.body.classList.contains('midnight')?'dark':'light')};if(localStorage.getItem('nlo_theme')==='dark')document.body.classList.add('midnight');
$('#prevMonth').onclick=()=>{state.month=new Date(state.month.getFullYear(),state.month.getMonth()-1,1);renderCalendar()};$('#nextMonth').onclick=()=>{state.month=new Date(state.month.getFullYear(),state.month.getMonth()+1,1);renderCalendar()};
$('#menuBtn').onclick=()=>{document.body.classList.add('drawer-open');$('#drawer').setAttribute('aria-hidden','false')};$('#drawerClose').onclick=()=>{document.body.classList.remove('drawer-open');$('#drawer').setAttribute('aria-hidden','true')};$$('#drawer a').forEach(a=>a.onclick=()=>$('#drawerClose').click());
$('#mobileMore').onclick=()=>{document.body.classList.add('sheet-open');$('#moreSheet').classList.add('open');$('#moreSheet').setAttribute('aria-hidden','false')};$('#sheetClose').onclick=closeSheet;$('#moreSheet').addEventListener('click',e=>{if(e.target===e.currentTarget)closeSheet()});function closeSheet(){document.body.classList.remove('sheet-open');$('#moreSheet').classList.remove('open');$('#moreSheet').setAttribute('aria-hidden','true')}
let deferred=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e});$('#installBtn').onclick=async()=>{if(deferred){deferred.prompt();await deferred.userChoice;deferred=null}else toast('On iPhone: Share → Add to Home Screen. On Android: use the browser Install App option.')};function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');clearTimeout(state.toastTimer);state.toastTimer=setTimeout(()=>t.classList.remove('show'),3500)}
window.addEventListener('scroll',()=>{$('#nav').classList.toggle('scrolled',scrollY>12)}, {passive:true});window.addEventListener('keydown',e=>{if(e.key==='Escape')closeSheet()});
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});load().catch(err=>{console.error(err);toast('Content could not be loaded. Check that data/content.json is available.')});
